### ISSUE TITLE
Problem runnning test.py

### ISSUE THREAD

**Issue by MeMyselfI** [pimoroni/skywriter-hat#12]
I installed the library successfully on a RPI 2, fresh installed Raspbian (updated everything) and after a reboot:

pi@raspberrypi:~/Pimoroni/skywriter $  sudo ./test.py
Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    import skywriter
  File "/usr/local/lib/python2.7/dist-packages/skywriter.py", line 482, in <modu                                              le>
    i2c.write_i2c_block_data(SW_ADDR, 0xa1, [0b00000000, 0b00011111, 0b00000000,                                               0b00011111])
IOError: [Errno 5] Input/output error
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/skywriter.py", line 473, in _exit
    stop_poll()
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/skywriter.py", line 473, in _exit
    stop_poll()
TypeError: 'NoneType' object is not callable

Any idea?

**Comment by MeMyselfI** [comment]
Got it working. Sorry. Nevermind.
